### ISSUE TITLE
Homepage - Testimonials - give the ability to add more than one testimonial. They will scroll.

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Fluid-Events#14]

**Comment by ccmorris** [comment]
a slideshow?

**Comment by ccmorris** [comment]
@tgascoigne14

**Comment by tgascoigne14** [comment]
Yes - like below but better ha. 
![screen shot 2018-01-24 at 11 30 18 am](https://user-images.githubusercontent.com/8631079/35344720-d02ef624-00fb-11e8-8e83-9c459cd0ba72.jpg)
