### ISSUE TITLE
Safari - Hire Fluid button sits below the header image. Please see screenshot

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Fluid-Events#16]
![screen shot 2018-01-25 at 3 58 38 pm](https://user-images.githubusercontent.com/8631079/35411979-b9e3c622-01e8-11e8-9528-659e433cdc27.png)

**Comment by ccmorris** [comment]
The position should be recalculated when the screen size changes and you scroll back up to the header image. Safari is not doing that right when the screen has been zoomed. I don't know how to fix this.
