### ISSUE TITLE
Work Detail - Logo - Horizontally center the logo in the left section

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Fluid-Events#4]
Please see the screenshots below. Some logos are larger than others due to the original file size and some logos are aligned with the title and others are not. Is there a way to format this page so it is more consistent? 
![screen shot 2018-01-11 at 10 53 13 am](https://user-images.githubusercontent.com/8631079/34833716-168c2b3e-f6be-11e7-820e-d47da21cebb9.png)
![screen shot 2018-01-11 at 10 53 32 am](https://user-images.githubusercontent.com/8631079/34833717-16a0669e-f6be-11e7-8f19-10b9db20cdd6.png)
![screen shot 2018-01-11 at 10 53 41 am](https://user-images.githubusercontent.com/8631079/34833718-16ae3a44-f6be-11e7-918c-f0de662a02e0.png)
![screen shot 2018-01-11 at 10 53 57 am](https://user-images.githubusercontent.com/8631079/34833719-16bd8756-f6be-11e7-9d7b-d42b7fd192fd.png)

**Comment by ccmorris** [comment]
Note to self: horizontally center the logos in the left section
