### ISSUE TITLE
Privacy Policy/Basic Page - Remove the white area at the bottom of page

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Fluid-Events#5]
![screen shot 2018-01-11 at 11 07 16 am](https://user-images.githubusercontent.com/8631079/34834424-f9e206fa-f6bf-11e7-884f-2873119472dd.png)
![screen shot 2018-01-11 at 11 09 12 am](https://user-images.githubusercontent.com/8631079/34834425-fa043b9e-f6bf-11e7-91a3-f661cb1b4bf2.png)

**Comment by ccmorris** [comment]
It's not that there is space at the bottom, the page is just not long enough. So do you want the footer background color to extend to the bottom of the screen? That is something we've done for other sites.

**Comment by tgascoigne14** [comment]
Interesting. Yes, please do extend the background colour
